---
# tasks file for ec2-setup

    - name: Create EC2 Instances
      amazon.aws.ec2_instance:
       name: "{{ item.name }}"
       key_name: "{{ ec2_keypair }}"
       instance_type: "{{ ec2_type }}"
       security_group: "{{ ec2_security }}"
       vpc_subnet_id: "{{ ec2_subnet }}"
       region: "{{ ec2_region }}"
       aws_access_key: "{{ec2_access_key}}"
       aws_secret_key: "{{ec2_secret_key}}"      
       network:
         assign_public_ip: true
       image_id: "{{ item.image }}"

      loop:
       - { image: "{{ ec2_ami1 }}", name: "{{ ec2_name1 }}" }
       - { image: "{{ ec2_ami2 }}", name: "{{ ec2_name2 }}" }
       - { image: "{{ ec2_ami3 }}", name: "{{ ec2_name3 }}" }