---
# tasks file for httpd
    - name: Install apache httpd
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes
        notify: start apache

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: Apache-webserver/httpd/files/index.html
        dest: /var/www/html
        owner: root
        group: root
        mode: '0644'
        notify: Restart apache